---
### boot_mode == kiosk

- name: hide-cursor plugin config
  ansible.builtin.copy:
    src: files/hide-cursor.xml
    dest: /usr/share/wayfire/metadata/hide-cursor.xml
    owner: root
    group: root
    mode: "0644"
  when: nkc_kiosk_boot_mode == "kiosk"

- name: hide-cursor plugin binary
  ansible.builtin.copy:
    src: files/libhide-cursor.so
    dest: /usr/lib/aarch64-linux-gnu/wayfire/libhide-cursor.so
    owner: root
    group: root
    mode: "0755"
  when: nkc_kiosk_boot_mode == "kiosk"

- name: copy wayfire configuration
  ansible.builtin.template:
    src: templates/bookworm/wayfire-kiosk.ini.j2
    dest: "/home/{{ ansible_user }}/.config/wayfire.ini"
    owner: "{{ ansible_user }}"
    mode: "0644"
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "kiosk"

### boot_mode == desktop

- name: copy wayfire configuration
  ansible.builtin.template:
    src: templates/bookworm/wayfire-desktop.ini.j2
    dest: "/home/{{ ansible_user }}/.config/wayfire.ini"
    owner: "{{ ansible_user }}"
    mode: "0644"
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "desktop"
