---
### boot_mode == kiosk

- name: install wtype
  ansible.builtin.apt:
    update_cache: true
    name:
      - wtype
    state: present
  when: nkc_kiosk_boot_mode == "kiosk"

- name: copy rc.xml configuration
  ansible.builtin.template:
    src: templates/trixie/rc.xml.j2
    dest: "/home/{{ ansible_user }}/.config/labwc/rc.xml"
    owner: "{{ ansible_user }}"
    mode: "0644"
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "kiosk"

- name: copy autostart configuration
  ansible.builtin.template:
    src: templates/trixie/autostart.j2
    dest: "/home/{{ ansible_user }}/.config/labwc/autostart"
    owner: "{{ ansible_user }}"
    mode: "0644"
  register: autostart_conf
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "kiosk"

- name: copy autostart configuration to etc
  ansible.builtin.template:
    src: templates/trixie/etc-autostart-kiosk.j2
    dest: /etc/xdg/labwc/autostart
    owner: root
    group: root
    mode: "0644"
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "kiosk"

- name: disable keyring
  ansible.builtin.command: bash -c "chmod a-x /usr/bin/gnome-keyring*"
  when: nkc_kiosk_boot_mode == "kiosk" and autostart_conf.changed

### boot_mode == desktop

- name: remove autostart configuration
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/labwc/autostart"
    state: absent
  when: nkc_kiosk_boot_mode == "desktop"

- name: copy autostart configuration to etc
  ansible.builtin.template:
    src: templates/trixie/etc-autostart-desktop.j2
    dest: /etc/xdg/labwc/autostart
    owner: root
    group: root
    mode: "0644"
  notify: Reboot Pi
  when: nkc_kiosk_boot_mode == "desktop"
