---
dependencies: []

galaxy_info:
  role_name: rpi
  author: Nils Ost (@nils-ost)
  description: configures Raspberry Pi to be a Kiosk, connected to NLPT-Kiosk-Controller
  license: GPL-3.0-or-later
  min_ansible_version: 2.13.9
  galaxy_tags:
    - nlpt
    - kiosk
    - raspberry
    - pi
    - display
    - projector
